"""Reporting and visualization module.

Generates HTML reports with equity curves, comparison dashboards,
and exports results to CSV/JSON formats.
"""

from __future__ import annotations

import csv
import json
from datetime import datetime
from pathlib import Path

import pandas as pd
from backtesting import Backtest

from .backtest import STRATEGIES, fetch_data


def _run_backtest_with_equity(
    strategy_name: str,
    symbol: str = "BTC-USD",
    start: str = "2018-01-01",
    end: str | None = None,
    cash: float = 100_000.0,
    commission: float = 0.001,
) -> tuple[dict, pd.Series]:
    """Run backtest and return both stats dict and equity curve."""
    strategy_cls = STRATEGIES[strategy_name]
    data = fetch_data(symbol, start, end)
    bt = Backtest(data, strategy_cls, cash=cash, commission=commission, exclusive_orders=True)
    stats = bt.run()

    # Extract equity curve
    equity = stats["_equity_curve"]["Equity"]

    result = {
        "strategy": strategy_name,
        "symbol": symbol,
        "period": f"{start} → {data.index[-1].strftime('%Y-%m-%d')}",
        "return_pct": round(float(stats["Return [%]"]), 2),
        "buy_hold_return_pct": round(float(stats["Buy & Hold Return [%]"]), 2),
        "win_rate_pct": round(float(stats["Win Rate [%]"]), 2) if not pd.isna(stats["Win Rate [%]"]) else 0.0,
        "num_trades": int(stats["# Trades"]),
        "max_drawdown_pct": round(float(stats["Max. Drawdown [%]"]), 2),
        "sharpe_ratio": round(float(stats["Sharpe Ratio"]), 2) if not pd.isna(stats["Sharpe Ratio"]) else 0.0,
        "final_equity": round(float(stats["Equity Final [$]"]), 2),
        "start_date": str(data.index[0].strftime("%Y-%m-%d")),
        "end_date": str(data.index[-1].strftime("%Y-%m-%d")),
    }

    return result, equity


# === HTML Report (#16) ===

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Backtest Report — {title}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
         margin: 2rem; background: #0d1117; color: #c9d1d9; }}
  h1 {{ color: #58a6ff; }}
  h2 {{ color: #79c0ff; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th, td {{ padding: 0.6rem 1rem; text-align: right; border: 1px solid #30363d; }}
  th {{ background: #161b22; color: #58a6ff; }}
  td:first-child, th:first-child {{ text-align: left; }}
  tr:nth-child(even) {{ background: #161b22; }}
  .positive {{ color: #3fb950; }}
  .negative {{ color: #f85149; }}
  .chart {{ width: 100%; height: 300px; margin: 1rem 0; }}
  svg {{ width: 100%; height: 100%; }}
  .legend {{ display: flex; gap: 1.5rem; margin: 0.5rem 0; }}
  .legend-item {{ display: flex; align-items: center; gap: 0.4rem; font-size: 0.9rem; }}
  .legend-dot {{ width: 12px; height: 12px; border-radius: 50%; }}
  footer {{ margin-top: 2rem; color: #8b949e; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>📊 {title}</h1>
<p>Generated: {date}</p>
{content}
<footer>Generated by meta-strategy backtesting engine</footer>
</body>
</html>"""

_COLORS = ["#58a6ff", "#3fb950", "#d2a8ff", "#f0883e", "#f85149", "#79c0ff"]


def _svg_equity_chart(equity_curves: dict[str, pd.Series], width: int = 800, height: int = 300) -> str:
    """Generate SVG equity curve chart."""
    if not equity_curves:
        return ""

    # Find global min/max
    all_values = []
    max_len = 0
    for eq in equity_curves.values():
        vals = eq.dropna().values
        all_values.extend(vals.tolist())
        max_len = max(max_len, len(vals))

    if not all_values:
        return ""

    y_min = min(all_values) * 0.95
    y_max = max(all_values) * 1.05
    y_range = y_max - y_min if y_max > y_min else 1

    margin = {"top": 20, "right": 20, "bottom": 30, "left": 80}
    plot_w = width - margin["left"] - margin["right"]
    plot_h = height - margin["top"] - margin["bottom"]

    lines = []
    legend_items = []

    for idx, (name, eq) in enumerate(equity_curves.items()):
        color = _COLORS[idx % len(_COLORS)]
        vals = eq.dropna().values
        points = []
        for i, v in enumerate(vals):
            x = margin["left"] + (i / max(max_len - 1, 1)) * plot_w
            y = margin["top"] + plot_h - ((v - y_min) / y_range) * plot_h
            points.append(f"{x:.1f},{y:.1f}")

        lines.append(
            f'<polyline points="{" ".join(points)}" fill="none" stroke="{color}" '
            f'stroke-width="1.5" opacity="0.9"/>'
        )
        legend_items.append(
            f'<span class="legend-item"><span class="legend-dot" '
            f'style="background:{color}"></span>{name}</span>'
        )

    # Y-axis labels
    y_labels = ""
    for i in range(5):
        val = y_min + (y_range * i / 4)
        y_pos = margin["top"] + plot_h - (i / 4) * plot_h
        y_labels += (
            f'<text x="{margin["left"] - 10}" y="{y_pos + 4}" '
            f'fill="#8b949e" font-size="11" text-anchor="end">${val:,.0f}</text>'
        )

    svg = f"""<div class="chart">
<svg viewBox="0 0 {width} {height}">
  <rect x="{margin['left']}" y="{margin['top']}" width="{plot_w}" height="{plot_h}" fill="none" stroke="#30363d"/>
  {y_labels}
  {"".join(lines)}
</svg>
</div>
<div class="legend">{"".join(legend_items)}</div>"""
    return svg


def generate_html_report(
    strategy_name: str,
    symbol: str = "BTC-USD",
    start: str = "2018-01-01",
    end: str | None = None,
    cash: float = 100_000.0,
    output_path: str | None = None,
) -> str:
    """Generate HTML report for a single strategy with equity curve."""
    result, equity = _run_backtest_with_equity(strategy_name, symbol, start, end, cash)

    # Build content
    ret_class = "positive" if result["return_pct"] > 0 else "negative"
    content = f"""
<h2>{result['strategy']} on {result['symbol']}</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Period</td><td>{result['period']}</td></tr>
  <tr><td>Return</td><td class="{ret_class}">{result['return_pct']:.2f}%</td></tr>
  <tr><td>Buy &amp; Hold</td><td>{result['buy_hold_return_pct']:.2f}%</td></tr>
  <tr><td>Win Rate</td><td>{result['win_rate_pct']:.2f}%</td></tr>
  <tr><td># Trades</td><td>{result['num_trades']}</td></tr>
  <tr><td>Max Drawdown</td><td class="negative">{result['max_drawdown_pct']:.2f}%</td></tr>
  <tr><td>Sharpe Ratio</td><td>{result['sharpe_ratio']:.2f}</td></tr>
  <tr><td>Final Equity</td><td>${result['final_equity']:,.2f}</td></tr>
</table>

<h2>Equity Curve</h2>
{_svg_equity_chart({strategy_name: equity})}
"""

    html = _HTML_TEMPLATE.format(
        title=f"{strategy_name} — {symbol}",
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        content=content,
    )

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(html)

    return html


# === Comparison Dashboard (#17) ===

def generate_dashboard(
    symbol: str = "BTC-USD",
    start: str = "2018-01-01",
    end: str | None = None,
    cash: float = 100_000.0,
    output_path: str | None = None,
) -> str:
    """Generate comparison dashboard for all strategies."""
    results_and_equity = {}
    for name in STRATEGIES:
        try:
            result, equity = _run_backtest_with_equity(name, symbol, start, end, cash)
            results_and_equity[name] = (result, equity)
        except Exception:
            pass

    # Table
    rows = ""
    for _name, (r, _) in results_and_equity.items():
        ret_class = "positive" if r["return_pct"] > 0 else "negative"
        rows += f"""<tr>
  <td>{r['strategy']}</td>
  <td class="{ret_class}">{r['return_pct']:.2f}%</td>
  <td>{r['buy_hold_return_pct']:.2f}%</td>
  <td>{r['win_rate_pct']:.2f}%</td>
  <td>{r['num_trades']}</td>
  <td class="negative">{r['max_drawdown_pct']:.2f}%</td>
  <td>{r['sharpe_ratio']:.2f}</td>
  <td>${r['final_equity']:,.2f}</td>
</tr>"""

    # Equity curves
    equity_curves = {name: eq for name, (_, eq) in results_and_equity.items()}

    if results_and_equity:
        valid = [(n, r) for n, (r, _) in results_and_equity.items() if r["num_trades"] > 0]
        best = max(valid, key=lambda x: x[1]["sharpe_ratio"]) if valid else None
        best_line = f'<p>🏆 <strong>Best Sharpe:</strong> {best[0]} ({best[1]["sharpe_ratio"]:.2f})</p>' if best else ""
    else:
        best_line = ""

    content = f"""
<h2>All Strategies — {symbol}</h2>
<table>
  <tr><th>Strategy</th><th>Return</th><th>Buy &amp; Hold</th><th>Win Rate</th>
      <th>Trades</th><th>Max DD</th><th>Sharpe</th><th>Final Equity</th></tr>
  {rows}
</table>
{best_line}

<h2>Equity Curves</h2>
{_svg_equity_chart(equity_curves)}
"""

    html = _HTML_TEMPLATE.format(
        title=f"Strategy Dashboard — {symbol}",
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        content=content,
    )

    if output_path:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(html)

    return html


# === Export (#18) ===

def export_results_json(results: list[dict], output_path: str) -> None:
    """Export backtest results to JSON."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(json.dumps(results, indent=2))


def export_results_csv(results: list[dict], output_path: str) -> None:
    """Export backtest results to CSV."""
    if not results:
        return
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [k for k in results[0] if k != "error"]
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(results)
